Fixes #10351: Make datasources behaviour on 404 request configurable
Normation/rudder-plugin-datasources pull request #12
Opened 2017-04-04 15:51 UTC by fanf

https://www.rudder-project.org/redmine/issues/10351

2017-04-05 08:27 UTC, VinceMacBuche commented
Can you rebase in one commit ?

2017-04-05 08:30 UTC, VinceMacBuche commented on src/main/resources/template/dataSourceManagement.html
> +              <label class="bloc"><a ng-click="toggleWell($event)">What to do when a queries for a node returns Error 404 (missing)?<span class="fa fa-chevron-right"></span></a></label>
What to do when a query for a Node returns a 404 error?

2017-04-05 10:58 UTC, VinceMacBuche commented on src/main/scala/com/normation/rudder/datasources/DataSourceSerializer.scala
> +            case JObject(fields) => fields.find( _.name == "name" ) match {
I would:

`case obj : JObject => obj \ "name" match 
case JString(Delete.name) => Full(Delete)
...
case JString(Default.name) => obj \ "value" match { case JNothing => Failure; case value => value)}`

2017-04-05 11:07 UTC, VinceMacBuche commented on src/main/scala/com/normation/rudder/datasources/UpdateHttpDataset.scala
> +      json.map( list => DataSource.nodeProperty(datasourceName.value, list.headOption.getOrElse("")) )
I had to read it thrice but it's ok :) ( In first attempt, i thought the None (NoChange) would be transformed into "" and would Delete the property but understood !!

2017-04-05 11:09 UTC, VinceMacBuche requested changes

2017-04-05 11:09 UTC, VinceMacBuche commented on src/test/scala/com/normation/rudder/datasources/UpdateHttpDatasetTest.scala
> +//  "Update on datasource" should {
Do you want it to be commented ??? I think we should remove if so

2017-04-05 13:05 UTC, fanf commented on src/test/scala/com/normation/rudder/datasources/UpdateHttpDatasetTest.scala
> +//  "Update on datasource" should {
nope :) it was because it took to long when testing, and eclipse does not help a lot to start only one test

2017-04-05 13:05 UTC, fanf commented on src/main/scala/com/normation/rudder/datasources/DataSourceSerializer.scala
> +            case JObject(fields) => fields.find( _.name == "name" ) match {
ok

2017-04-05 13:05 UTC, fanf commented on src/main/resources/template/dataSourceManagement.html
> +              <label class="bloc"><a ng-click="toggleWell($event)">What to do when a queries for a node returns Error 404 (missing)?<span class="fa fa-chevron-right"></span></a></label>
if you prefer

2017-04-05 16:03 UTC, fanf commented
PR rebased

2017-04-05 16:06 UTC, fanf commented
PR rebased

2017-04-06 09:03 UTC, VinceMacBuche approved these changes
👍

2017-04-06 09:03 UTC, Normation-Quality-Assistant commented
OK, merging this PR

2017-04-06 09:04 UTC, merged